language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
script:
  - ./mvnw test -B -DforceIntegrationTests=true
install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_script:
  - gcloud beta emulators pubsub start &
  - while [ ! -f ~/.config/gcloud/emulators/pubsub/env.yaml ]; do sleep 1; done
  - $(gcloud beta emulators pubsub env-init)
before_install:
  - openssl aes-256-cbc -K $encrypted_1ef8dfbdb114_key -iv $encrypted_1ef8dfbdb114_iv -in travis.tar.gz.enc -out travis.tar.gz -d
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-189.0.0-linux-x86_64.tar.gz
  - tar -xvzf google-cloud-sdk-189.0.0-linux-x86_64.tar.gz
  - export PATH=$PWD/google-cloud-sdk/bin:$PATH
  - gcloud components update --quiet
  - gcloud components install beta pubsub-emulator --quiet
  - tar -xzf travis.tar.gz
  - gcloud auth active-service-account --key-file travis/admin.json
  - gcloud config set project spring-cloud-gcp-ci