name: Linkage Check

on:
  pull_request:
    branches:
      - 'dependabot/**'
  workflow_dispatch:
  schedule:
    - cron: '00 9 * * *' # 09:00 UTC every day

jobs:
  linkageCheck:
    if: github.repository == 'GoogleCloudPlatform/spring-cloud-gcp'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d' --utc)"
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        id: mvn-cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-unified-${{ steps.date.outputs.date }}
      - name: Maven go offline
        id: mvn-offline
        if: steps.mvn-cache.outputs.cache-hit != 'true'
        run: ./mvnw compile dependency:go-offline
      - name: install
        # install before running Linkage Checker
        run: |
          ./mvnw \
             --batch-mode \
             --show-version \
             --threads 1.5C \
             --define skipTests=true \
             --define maven.javadoc.skip=true \
             --errors \
             install
      - name: run linkage checker
        run: |
          ./mvnw \
            --activate-profiles linkage-check \
            --projects spring-cloud-gcp-dependencies \
            --batch-mode \
            --show-version \
            --threads 1.5C \
            --define skipTests=true \
            --define maven.javadoc.skip=true \
            --errors \
            verify
